server:
  port: 8080
  servlet:
    context-path: /cyx

spring:
  application:
    name: cyx
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 2MB
      location: E:/tmp
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.111:3306/mysql_study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 180000
  data:
    redis:
      host: 192.168.1.111
      port: 6379
      password: 123456
      database: 0
      connect-timeout: 2000

#mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: delFlag
  type-aliases-package: com.soft.base.entity, com.soft.base.request, com.soft.base.vo, com.soft.base.dto

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/develop.log

knife4j:
  production: false
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体列表


#jwt
jwt:
  #密钥
  secret-key: abcdefghijklmnopq1907452460
  #单位秒；1小时过期
  expire: 3600000

#AES密钥
aes:
  secret-factor: T8MjuJQtXJ0rT8KLZQRnUw==

#minio云存储
minio:
  url: http://192.168.1.111:9002
  accessKey: admin
  secretKey: 123456789
  bucket: cyx

#不鉴权url
permit:
  urls:
    - /doc.html
    - /auth/**